name: Gpt Retrieval - Azure CD/CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Bouvet-Shenanigans.GptRetrieval/**"
      - ".github/workflows/gptRetrieval.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./Bouvet-Shenanigans.GptRetrieval
          push: true
          build-args: |
            version=latest
          tags: ${{ secrets.ACR_ENDPOINT }}/gptretrieval:latest
