name: Pulumi
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Bouvet-Shenanigans.Pulumi/*"
      - ".github/workflows/pulumi.yml"

permissions:
  id-token: write
  contents: read

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Azure login
        uses: azure/login@v1
        with:
          enable-AzPSSession: true
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy pulumi
        uses: pulumi/actions@v4
        with:
          work-dir: ./Bouvet-Shenanigans.Pulumi
          command: up
          stack-name: sivertheisholt/BouvetShenanigans.Pulumi/dev
          # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_CONFIG: '{"azure-native:location":"West Europe"}'
