name: Pulumi
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: cd ./Bouvet-Shenanigans.Pulumi;

      - name: Deploy pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: sivertheisholt/BouvetShenanigans.Pulumi/dev
          # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
